### ISSUE TITLE
Fix/Salvage More Flight Data

### ISSUE THREAD

**Issue by JacksonElia** [NCSU-High-Powered-Rocketry-Club/AirbrakesV2#52]
We have very few data sets that we can use to test our code, but we have older data sets that could be converted to work with our code

For these ones you will have to convert the csv headers to match what our sim uses, they're missing altitude and compensated acceleration
- [ ] ARDUFlightData_Cato_PDF 
- [ ] ARDUFlightData_Cato_VDF
- [ ] ARDUFlightData_subCato

**Comment by wlsanderson** [comment]
After looking at the flight data, it is most likely unusable with the simulation. The IMU that was used for these flights had an acceleration cap at 5G's, rendering the acceleration in the motor burn phase unreliable. Because we rely on accurate velocity calculations pretty heavily, I don't think these datasets will be able to provide much, especially due to the lack of altitude data as well.
